version: "3.8"

services:
  mfe-host:
    build:
      context: ./mfe-host
    ports:
      - "4173:80"
    container_name: mfe-host

  mfe-console:
    build:
      context: ./mfe-console
    ports:
      - "4174:80"
    container_name: mfe-console
