version: "3.8"

services:
  mfe-host:
    build:
      context: ./mfe-host
    ports:
      - "8080:80"
    container_name: mfe-host

  mfe-console:
    build:
      context: ./mfe-console
    ports:
      - "8081:80"
    container_name: mfe-console
