# Dockerfile

# 👉 Etapa 1: Build con Node
FROM node:22-alpine AS builder
WORKDIR /app

# Copia dependencias y código
COPY package*.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

# Build del MFE (genera el remoteEntry.js)
RUN yarn build

# 👉 Etapa 2: Imagen final con NGINX
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html

# Reemplazamos la config por una personalizada
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponer puerto 80 para servir
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
