# Etapa 1: Build
FROM node:22-alpine AS builder
WORKDIR /app

# Copiamos solo los archivos de dependencias primero
COPY package*.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Argumento para inyectar la URL del MFE remoto
ARG VITE_CONSOLE_REMOTE_URL
ENV VITE_CONSOLE_REMOTE_URL=$VITE_CONSOLE_REMOTE_URL

# Ahora sí copiamos el resto del código
COPY . .

# Compilamos el frontend
RUN yarn build

# Etapa 2: NGINX server
FROM nginx:alpine

# Copiamos el resultado del build al directorio público de NGINX
COPY --from=builder /app/dist /usr/share/nginx/html

# Copiamos nuestra configuración personalizada de NGINX
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
