name: Build and Push MFEs to GCP

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: mfe-project-464600
      REGION: us-central1
      REPO_NAME: mfe-registry

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and push mfe-host
        run: |
          docker build \
            --build-arg VITE_CONSOLE_REMOTE_URL=http://34.123.45.67/console/assets/remoteEntry.js \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/mfe-host:latest \
            ./mfe-host

          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/mfe-host:latest

      - name: Build and push mfe-console
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/mfe-console:latest ./mfe-console
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/mfe-console:latest
